import { Card } from './card';

export const deck: Card[] = [
  { id: 'the_fool', name: 'The Fool' },
  { id: 'the_magician', name: 'The Magician' },
  { id: 'the_high_priestess', name: 'The High Priestess' },
  { id: 'the_empress', name: 'The Empress' },
  { id: 'the_emperor', name: 'The Emperor' },
  { id: 'the_hierophant', name: 'The Hierophant' },
  { id: 'the_lovers', name: 'The Lovers' },
  { id: 'the_chariot', name: 'The Chariot' },
  { id: 'strength', name: 'Strength' },
  { id: 'the_hermit', name: 'The Hermit' },
  { id: 'wheel_of_fortune', name: 'Wheel of Fortune' },
  { id: 'justice', name: 'Justice' },
  { id: 'the_hanged_man', name: 'The Hanged Man' },
  { id: 'death', name: 'Death' },
  { id: 'temperance', name: 'Temperance' },
  { id: 'the_devil', name: 'The Devil' },
  { id: 'the_tower', name: 'The Tower' },
  { id: 'the_star', name: 'The Star' },
  { id: 'the_moon', name: 'The Moon' },
  { id: 'the_sun', name: 'The Sun' },
  { id: 'judgement', name: 'Judgement' },
  { id: 'the_world', name: 'The World' },
];
