name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: 'Run linting'
    uses: ./.github/workflows/node-job.yml
    secrets: inherit
    with:
      command: npm run lint

  test:
    name: 'Run Unit tests'
    uses: ./.github/workflows/node-job.yml
    secrets: inherit
    with:
      command: npm test

  build:
    name: 'Build application'
    uses: ./.github/workflows/node-job.yml
    secrets: inherit
    with:
      command: npm run build

  test_coverage:
    name: 'Run tests with coverage'
    uses: ./.github/workflows/node-job.yml
    secrets: inherit
    with:
      command: npm run test:cov

  test_migration:
    name: 'Run tests with migration'
    uses: ./.github/workflows/migration-test.yml
